version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: go-server
    ports:
      - "8080:8080"           

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: web-client
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true   
    depends_on:
      - server     